@token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQ1VTVE9NRVIiLCJzdWIiOiJoaW1hbnNodXNhaW5pYi4xNTlAZ21haWwuY29tIiwiaWF0IjoxNzY3ODY5NjU2LCJleHAiOjE3Njc4Njk2NzF9.AcJ9HT2by4p1p1O7gkALYe84FMjSFOmuN1TwW0B8QVI

### Get customers
GET http://localhost:8080/customers
Authorization: Bearer {{token}}


### Get Orders
GET http://localhost:8080/orders
Authorization: Bearer {{token}}

### Get Products
GET http://localhost:8080/products
Authorization: Bearer {{token}}

### Create Product
POST http://localhost:8080/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name" : "Mobile",
  "price": "560"
}

### Test
POST http://localhost:8080/products/test
Authorization: Bearer {{token}}

### Signup
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "himanshusaini03456@gmail.com",
  "password": "1234"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "himanshusainib.159@gmail.com",
  "password": "1234"
}
