@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQ1VTVE9NRVIiLCJzdWIiOiJoaW1hbnNodXNhaW5pYi4xNTlAZ21haWwuY29tIiwiaWF0IjoxNzY3OTMyNjIzLCJleHAiOjE3Njc5MzI2ODN9.RTOltDJIjmpmPpSclQpggIntSm3A51t-9OYL62pELP8

### Get customers
GET {{baseUrl}}/customers
Authorization: Bearer {{token}}


### Get Orders
GET {{baseUrl}}/orders
Authorization: Bearer {{token}}

### Get Products
GET {{baseUrl}}/products
Authorization: Bearer {{token}}

### Create Product
POST {{baseUrl}}/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name" : "Mobile",
  "price": "560"
}

### Signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "himanshusaini03456@gmail.com",
  "password": "1234"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "himanshusainib.159@gmail.com",
  "password": "1234"
}

### Refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken":"70113b00-87b6-4efa-a531-c44d504608af"
}

